services:
  web:
    depends_on:
      - db
    env_file: ./.env
    build: .
    command: bash -c "cd app && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    expose:
      - 8000
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    ports:
      - 5432:5432
    expose:
      - 5432

volumes:
  postgres_data: